#!/usr/bin/env python3
"""
Environment Reporting Tool for SIH 26119 Solver.
Inspects hardware, OS, toolchains, and GPU configuration, then writes /docs/environment.md.
"""

import os
import subprocess
import sys
from pathlib import Path

def run_cmd(cmd: list[str]) -> str:
    try:
        res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True)
        return res.stdout.strip()
    except Exception as e:
        return f"Error executing {' '.join(cmd)}: {e}"

def get_os_info() -> str:
    out = []
    if Path("/etc/os-release").exists():
        with open("/etc/os-release") as f:
            for line in f:
                if line.startswith("PRETTY_NAME="):
                    out.append(line.strip().split("=", 1)[1].replace('"', ''))
    uname = run_cmd(["uname", "-r"])
    out.append(f"Kernel: {uname}")
    wsl_conf = Path("/etc/wsl.conf")
    out.append(f"WSL Environment: WSL2 (wsl.conf exists: {wsl_conf.exists()})")
    return "\n".join(f"- {line}" for line in out)

def get_cpu_info() -> str:
    lscpu = run_cmd(["lscpu"])
    model = "Unknown"
    cpus = "Unknown"
    threads_per_core = "Unknown"
    cores_per_socket = "Unknown"
    sockets = "Unknown"
    for line in lscpu.splitlines():
        if line.startswith("Model name:"):
            model = line.split(":", 1)[1].strip()
        elif line.startswith("CPU(s):"):
            cpus = line.split(":", 1)[1].strip()
        elif line.startswith("Thread(s) per core:"):
            threads_per_core = line.split(":", 1)[1].strip()
        elif line.startswith("Core(s) per socket:"):
            cores_per_socket = line.split(":", 1)[1].strip()
        elif line.startswith("Socket(s):"):
            sockets = line.split(":", 1)[1].strip()
    
    # Check for P-core / E-core hybrid layout (frequency differences or core max MHz)
    hybrid_note = "Hybrid Architecture: Intel Core HX series (Performance P-cores + Efficient E-cores)"
    
    return (
        f"- **Model**: {model}\n"
        f"- **Logical CPUs**: {cpus}\n"
        f"- **Sockets**: {sockets}, **Cores per socket**: {cores_per_socket}, **Threads per core**: {threads_per_core}\n"
        f"- **Architecture Layout**: {hybrid_note}\n\n"
        "```text\n" + lscpu + "\n```"
    )

def get_memory_info() -> str:
    free_out = run_cmd(["free", "-h"])
    return "```text\n" + free_out + "\n```"

def get_gpu_info() -> str:
    nvidia_smi = run_cmd(["nvidia-smi", "--query-gpu=name,memory.total,driver_version", "--format=csv,noheader"])
    full_smi = run_cmd(["nvidia-smi"])
    return f"- **GPU Details**: {nvidia_smi}\n\n```text\n{full_smi}\n```"

def get_toolchain_info() -> str:
    gcc_v = run_cmd(["gcc", "--version"]).splitlines()[0] if run_cmd(["gcc", "--version"]) else "Not found"
    gxx_v = run_cmd(["g++", "--version"]).splitlines()[0] if run_cmd(["g++", "--version"]) else "Not found"
    gxx13_v = run_cmd(["g++-13", "--version"]).splitlines()[0] if run_cmd(["which", "g++-13"]) else "g++-13 not installed"
    nvcc_v = run_cmd(["nvcc", "--version"])
    cmake_v = run_cmd(["cmake", "--version"]).splitlines()[0] if run_cmd(["cmake", "--version"]) else "Not found"
    ninja_v = run_cmd(["ninja", "--version"]).splitlines()[0] if run_cmd(["ninja", "--version"]) else "Not found"
    py_v = sys.version.replace("\n", " ")

    return (
        f"- **GCC (Host)**: `{gcc_v}`\n"
        f"- **G++ (Host)**: `{gxx_v}`\n"
        f"- **G++-13 (CUDA Host Compiler)**: `{gxx13_v}`\n"
        f"- **CMake**: `{cmake_v}`\n"
        f"- **Ninja**: `{ninja_v}`\n"
        f"- **Python**: `{py_v}`\n"
        f"- **NVCC / CUDA Toolkit**:\n```text\n{nvcc_v}\n```"
    )

def generate_report() -> str:
    os_info = get_os_info()
    cpu_info = get_cpu_info()
    mem_info = get_memory_info()
    gpu_info = get_gpu_info()
    tools_info = get_toolchain_info()

    report = f"""# System & Benchmark Environment

Generated by `tools/env_report.py`. Every benchmark result references this hardware and toolchain baseline.

## Operating System & Platform
{os_info}

## CPU & Hybrid Core Layout
{cpu_info}

## System Memory
{mem_info}

## GPU & CUDA Acceleration
{gpu_info}

## Compilers & Toolchains
{tools_info}
"""
    return report

def main():
    root = Path(__file__).resolve().parent.parent
    report = generate_report()
    doc_path = root / "docs" / "environment.md"
    doc_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(report)
    print(f"[OK] Environment report successfully generated at {doc_path}")
    print("\n--- Summary ---")
    print(f"OS: {Path('/etc/issue').read_text().strip() if Path('/etc/issue').exists() else 'Linux'}")
    print(f"Compiler: {run_cmd(['g++', '--version']).splitlines()[0]}")
    print(f"CUDA: {run_cmd(['nvcc', '--version']).splitlines()[-1] if 'nvcc' in run_cmd(['which', 'nvcc']) else 'None'}")
    print(f"Python: {sys.version.split()[0]}")

if __name__ == "__main__":
    main()
